Logic of components
Tarakann119/noLabel-game pull request #18
Opened 2023-03-11 09:25 UTC by Tarakann119

### нормально выглядит, все работает
TODO:привести профиль в порядок

2023-03-11 09:29 UTC, Zimer-D approved these changes

2023-03-11 09:37 UTC, ArkadiySamokhvalov commented on packages/client/package.json
> +    "stylelint-config-standard-scss": "^7.0.1",
Остался лишний пакет stylelint-config-standard-scss.

2023-03-11 09:51 UTC, Tarakann119 commented on packages/client/package.json
> +    "stylelint-config-standard-scss": "^7.0.1",
удалил

2023-03-11 09:59 UTC, Antidods approved these changes

2023-03-11 10:08 UTC, tamerlan2451 approved these changes

2023-03-11 13:39 UTC, ArkadiySamokhvalov approved these changes

2023-03-11 13:40 UTC, tmj1 approved these changes

2023-03-11 15:57 UTC, Olegas requested changes

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/Layout.tsx
> +  function RequireAuth() {
Не надо функции объявлять внутри компонента без необходимости. Тут точно нет необходимости. 
Такой подход дает постоянное создание нового экземпляра функции что в конечном итоге дает лишние перерисовки и нагрузку на Garbage Collector

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/Autification/slice.ts
> +      state.user.phone = action.payload.phone;
Выглядит так что это state.user = action.payload

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/Autification/slice.ts
> +      state.user.phone = null;
А не проще сделать state.user = null?

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/Header/index.tsx
> +  const LogOut = async () => {
Функции лучше называть с маленькой буквы. С большой называть типы, классы, компоненты

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/Header/index.tsx
> +  };
Это кстати еще одна чистая функция которую можно не объявлять каждый раз а вынести из компонента

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/Header/index.tsx
> +                clickButton={() => LogOut()}
Можно просто clickButton={LogOut}

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/InputWrapper/index.scss
> +    //height: 56px;
Давайте не будем оставлять закомментированный код

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/Leaderboard/index.tsx
> +    <div className='board'>
Немного странный стиль кода - JSX-аттрибуты в одинарных кавычках...

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/Leaderboard/index.tsx
> +      {/*<Button className='board__button' text={'Начать игру'} />*/}
Давайте не будем оставлять закомментированный код. Или хотя бы подписывать зачем он оставлен

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/Theme/index.tsx
> +        <div className='navigation-link'> Нективная тема</div>
Тут кажется лишний пробел в начале

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/components/UserCard/index.tsx
> +        <Avatar src={avatarUrl} size='header' onClick={() => clickCard} />
Тут видимо забыли скобки в clickCard или по факту хотели написать onClick={clickCard}

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/pages/Forum/index.tsx
> +  const navigate = useNavigate();
Так давайте сразу удалим раз не используется

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/pages/LoginPage/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Вроде как и fieldError и setFieldError используются. Зачем гасить тут линтер?

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/pages/LoginPage/index.tsx
> +    axios(`https://ya-praktikum.tech/api/v2/auth/user`, {
А вы не хотите убрать это в thunk? А то получается что половина логики в редаксе а половина тут в компоненте

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
> +preview: string,
Что-то с отступами

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
> +    console.log(11,file)
Очень много отладочного вывода. Его нормально использовать при разработке, но когда все готово - лучше убрать.

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/pages/RegisterPage/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Зачем гасить правило? Если не используете так и удалите просто из кода

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/pages/RegisterPage/index.tsx
> +              {errors.second_name && touched.second_name ? <div>{errors.second_name}</div> : null}
Вот эта история с проверкой наличия ошибки повторяется в каждом поле. Не лучше ее вынести куда-то, например в InputWrapper или в сам Field?

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/ui/HeaderH1/index.tsx
> +  return <h1 className={classNames('h1')}>{label}</h1>;
А для чего тут classNames? Тут же одна константная строка.

2023-03-11 15:57 UTC, Olegas commented on packages/client/src/ui/Loader/index.tsx
> +        event.preventDefault();
А для чего это нужно?

2023-03-11 15:57 UTC, Olegas commented on packages/client/utils/generateId/index.tsx
> +export const uuid =()=> {
Пробел после = пропущен. Прикрутите prettier? Он за вас все это будет делать

2023-03-11 15:57 UTC, Olegas commented on packages/client/utils/generateId/index.tsx
> +    );
Очень крутая функция! 👍

2023-03-11 15:58 UTC, Olegas commented on packages/client/src/components/Leaderboard/index.tsx
> +    <div className='board'>
Тут не настаиваю, но чаще вижу двойные в HTML-разметке. Кажется более общепринятый стиль.

2023-03-12 08:27 UTC, Tarakann119 commented on packages/client/src/components/Autification/slice.ts
> +      state.user.phone = null;
В данном случае  не думаю что стоит делать сущность user=null так как это может привести к дополнительным ошибкам и потребуются доп.проверки чтобы избежать null reference exception +необходима инициализация user в другом месте

2023-03-12 19:07 UTC, Olegas reviewed
Не все замечания исправлены. Если где-то не согласны или прямо сейчас почему-то нет возможности исправить - давайте обсудим.

2023-03-13 09:42 UTC, Zimer-D commented
Добрый день, получил ваше ревью, что не все замечания исправлены, я не
исправил в packages/client/src/components/Autification/slice.ts на
state.user = null т.к. это ломает типизацию и требует инициализировать
user'а в другом месте, дописывать в текущую типизацию что-то типа
user.id: string|null мне кажется тоже несовсем корректным


вс, 12 мар. 2023 г. в 22:07, Oleg Elifantiev ***@***.***>:
>
> @Olegas commented on this pull request.
>
> Не все замечания исправлены. Если где-то не согласны или прямо сейчас почему-то нет возможности исправить - давайте обсудим.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.Message ID: ***@***.***>

2023-03-13 17:35 UTC, Olegas commented
@Zimer-D взял первое попавшееся наугад - [packages/client/src/components/Theme/index.tsx](https://github.com/Tarakann119/noLabel-game/pull/18/files#diff-471eddb7c94018000d2e1df02e0985d3597a4417260152fc74647304e84cd1a2)
Про лишний пробел в тексте - не исправлено.

Следующее наугад про функцию LogOut - не исправлено.

Про state.user = null  вопросов нет, согласен, зарезолвил его.

2023-03-13 18:06 UTC, Tarakann119 commented on packages/client/src/components/Header/index.tsx
> +  const LogOut = async () => {
![image](https://user-images.githubusercontent.com/126061866/224790081-9081c7a3-79f8-4a2e-85ef-9c5b41482001.png)

2023-03-13 18:08 UTC, Tarakann119 commented on packages/client/src/pages/RegisterPage/index.tsx
> +              {errors.second_name && touched.second_name ? <div>{errors.second_name}</div> : null}
![image](https://user-images.githubusercontent.com/126061866/224790369-24ba0cf8-1045-464b-9d6c-922122d25cf9.png)
реализовали немного по-другому

2023-03-13 18:08 UTC, Tarakann119 commented on packages/client/src/ui/HeaderH1/index.tsx
> +  return <h1 className={classNames('h1')}>{label}</h1>;
![image](https://user-images.githubusercontent.com/126061866/224790540-5090bb4c-b9ca-4862-be59-aee41a1461e0.png)

2023-03-13 18:09 UTC, Tarakann119 commented on packages/client/src/ui/Loader/index.tsx
> +        event.preventDefault();
![image](https://user-images.githubusercontent.com/126061866/224790821-5bcade8f-a63d-45b9-af1c-7deaf80cd50c.png)

2023-03-13 18:10 UTC, Tarakann119 commented on packages/client/utils/generateId/index.tsx
> +export const uuid =()=> {
![image](https://user-images.githubusercontent.com/126061866/224791013-1cca012b-4e49-447b-a047-8dea5a8d5fbd.png)
претир прикручен

2023-03-13 18:11 UTC, Tarakann119 commented on packages/client/src/components/InputWrapper/index.scss
> +    //height: 56px;
![image](https://user-images.githubusercontent.com/126061866/224791390-6903fe99-7047-4800-bab7-9bce6e697d50.png)

2023-03-13 18:12 UTC, Tarakann119 commented on packages/client/src/components/Leaderboard/index.tsx
> +    <div className='board'>
![image](https://user-images.githubusercontent.com/126061866/224791559-25305861-49f8-4d56-9e55-45a9d50aedb9.png)

2023-03-13 18:14 UTC, Tarakann119 commented on packages/client/src/components/UserCard/index.tsx
> +        <Avatar src={avatarUrl} size='header' onClick={() => clickCard} />
![image](https://user-images.githubusercontent.com/126061866/224792050-d02d5702-c8f1-4b6e-8ed8-2b8da68ba79d.png)

2023-03-13 18:14 UTC, Tarakann119 commented on packages/client/src/pages/Forum/index.tsx
> +  const navigate = useNavigate();
![image](https://user-images.githubusercontent.com/126061866/224792253-f408a9ac-0329-4405-8516-63d23921301b.png)

2023-03-13 18:15 UTC, Tarakann119 commented on packages/client/src/pages/LoginPage/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
![image](https://user-images.githubusercontent.com/126061866/224792441-85ed89e2-22bb-4189-8a89-d2d91b52206b.png)

2023-03-13 18:18 UTC, Tarakann119 commented on packages/client/src/pages/LoginPage/index.tsx
> +    axios(`https://ya-praktikum.tech/api/v2/auth/user`, {
![image](https://user-images.githubusercontent.com/126061866/224793506-ddeffcf5-06b4-4f98-a10d-f739b62d6140.png)

2023-03-13 18:18 UTC, Tarakann119 commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
> +preview: string,
![image](https://user-images.githubusercontent.com/126061866/224793621-aaa9f957-4584-4980-9db4-65fe691ccaa4.png)

2023-03-13 18:21 UTC, Tarakann119 commented on packages/client/src/pages/RegisterPage/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
удалено

2023-03-13 18:35 UTC, Olegas commented on packages/client/src/pages/LoginPage/index.tsx
> +      responseType: 'json',
Вот тут работа с сетью не в thunk

2023-03-13 18:36 UTC, Olegas commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
>    const _updateAvatar = async () => {
Для чего эта функция называется с _? Это что-то означает?

2023-03-13 18:38 UTC, Olegas commented on packages/client/src/pages/LoginPage/index.tsx
> +            dispatch(loginUser.call(data));
А что такое loginUser.call? Зачем нужно так функцию вызывать а не просто dispatch(loginUser(data))?

2023-03-13 18:39 UTC, Olegas commented on packages/client/src/components/Autification/slice.ts
> +      toast.success('Данные пользователя загружены!');
Тут вот странно получилось. Работа со стейтом явно знает о каком-то интерфейсном элементе toast.

2023-03-13 18:40 UTC, Olegas commented on packages/client/src/components/Autification/slice.ts
> +export const loginUser = createAsyncThunk('user/login', async (data, { dispatch }) => {
Это действие - не login. Это что-то типа getCurrentUser. Login это когда мы входим в систему

2023-03-13 18:42 UTC, Tarakann119 commented on packages/client/src/pages/RegisterPage/index.tsx
> +                message={`${errors.first_name}`}
поправил

2023-03-14 05:45 UTC, Olegas approved these changes

2023-03-14 05:46 UTC, Olegas requested changes
Случаной поставил апрув (

2023-03-14 07:15 UTC, Tarakann119 commented on packages/client/src/pages/LoginPage/index.tsx
> +            dispatch(loginUser.call(data));
исправлено

2023-03-14 07:17 UTC, Tarakann119 commented on packages/client/src/components/Autification/slice.ts
> +export const loginUser = createAsyncThunk('user/login', async (data, { dispatch }) => {
переименованно

2023-03-14 08:36 UTC, Tarakann119 commented on packages/client/src/pages/LoginPage/index.tsx
> +      responseType: 'json',
исправлено

2023-03-14 08:37 UTC, Tarakann119 commented on packages/client/src/components/Autification/slice.ts
> +      toast.success('Данные пользователя загружены!');
Объясните пожалуйста что неправильно

2023-03-14 11:32 UTC, Tarakann119 commented on packages/client/src/pages/RegisterPage/index.tsx
> +              {errors.second_name && touched.second_name ? <div>{errors.second_name}</div> : null}
исправлено

2023-03-14 18:44 UTC, Olegas requested changes

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/pages/LoginPage/index.tsx
> +  // .required('Required'),
Не оставляйте пожалуйста закомментированный код

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/pages/LoginPage/index.tsx
> +  // const [passErr, setPassErr] = useState(false);
Не оставляйте пожалуйста закомментированный код

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/pages/LoginPage/index.tsx
> +              name={'login'}
Тут просто name='login' и везде так. Давайте писать одинаково. Не понятно почему тут так, а несколько строк ниже - по другому. Надо что бы везде было консистентно

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/components/Autification/slice.ts
> +export const handleSubmitLogin = createAsyncThunk(
Это действие должно называться на Login (вход) а Sigin (регистрация). Вы же здесь регистрируете нового пользователя

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/components/Autification/slice.ts
> +      toast.success('Данные пользователя загружены!');
У вас тут в работу со стейтом пролезла работа с интерфейсом. Это разные слои приложения. Грубо говоря пример: завтра вы решите использовать другую библиотеку для отображения ошибок или будете показывать их не глобально а в точке где ошибка случилась. И что бы это сделать, вам придется лезть в thunk и action creators. Это нарушает структуру приложения, нарушает ответственности уровней. Показ уведомления об ошибке - это не состояние приложения.

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/components/MainLayout/index.tsx
> +//   )
Нужно убрать закомментированный код

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/components/Theme/index.tsx
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
А зачем тут гасить предупреждение? Нужно определить тип для пропсов и не придется ничего отключать

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/components/Theme/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
И тут можно не отключать линтер если типизировать ваш стейт. Посмотрите вот тут документацию как это можно сделать: https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-state-type

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
>    }, []);
Тут не хватает зависимости от files. При смене набора файлов этот useEffect не отработает

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
>    const [files, setFiles] = useState<any[]>([]);
Зачем тут any? Разве тут не FileType[]

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
>    }, []);
Посмотрите вот на это правило https://www.npmjs.com/package/eslint-plugin-react-hooks оно позволяет предотвратить такие ошибки

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/pages/Profile/ChangePassword.tsx
> +              label={'Повторите пароль'}
Еще одно место где половина файла написана одним стилем (type={'password'}) а другая - другим (type='submit')

2023-03-14 18:44 UTC, Olegas commented on packages/client/src/ui/HeaderH1/index.tsx
> +  return <h1 className={'h1'}>{label}</h1>;
Тут тоже стиль передачи пропсов отличается (className={'h1'} -> className='h1')

2023-03-14 18:44 UTC, Olegas commented on yarn-error.log
Файл с ошибками yarn думаю не стоит комитить в проект

2023-03-15 05:46 UTC, Tarakann119 commented on packages/client/src/ui/HeaderH1/index.tsx
> +  return <h1 className={'h1'}>{label}</h1>;
исправлено

2023-03-15 05:47 UTC, Tarakann119 commented on packages/client/src/pages/Profile/ChangePassword.tsx
> +              label={'Повторите пароль'}
исправлено

2023-03-15 06:04 UTC, Tarakann119 commented on packages/client/src/components/Autification/slice.ts
> +export const handleSubmitLogin = createAsyncThunk(
нет, это функция на вход(логин)

2023-03-15 06:32 UTC, Tarakann119 commented on packages/client/src/pages/LoginPage/index.tsx
> +  // const [passErr, setPassErr] = useState(false);
убрал

2023-03-15 06:32 UTC, Tarakann119 commented on packages/client/src/pages/LoginPage/index.tsx
> +  // .required('Required'),
убрал

2023-03-15 06:35 UTC, Tarakann119 commented on packages/client/src/components/MainLayout/index.tsx
> +//   )
убрал

2023-03-15 06:35 UTC, Tarakann119 commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
>    }, []);
добавил

2023-03-15 06:35 UTC, Tarakann119 commented on packages/client/src/pages/Profile/ChangeAvatar.tsx
>    const [files, setFiles] = useState<any[]>([]);
добавил

2023-03-15 06:39 UTC, Tarakann119 commented on packages/client/src/components/Theme/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
поправил

2023-03-15 06:40 UTC, Tarakann119 commented on packages/client/src/components/Theme/index.tsx
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
поправил

2023-03-15 19:35 UTC, Olegas commented on packages/client/src/components/Autification/slice.ts
> +export const handleSubmitLogin = createAsyncThunk(
Упс, я ошибся (

2023-03-15 19:38 UTC, Olegas approved these changes
👍

2023-03-16 06:29 UTC, merged