presisit+fix
Tarakann119/noLabel-game pull request #23
Opened 2023-03-16 12:12 UTC by Zimer-D

### presist + пофиксил в функции логина пользователя

2023-03-16 12:24 UTC, tamerlan2451 approved these changes

2023-03-16 12:29 UTC, Antidods requested changes
Дим, почему удалены файлы стилей? Или что то не правильно понял?

2023-03-16 14:05 UTC, ArkadiySamokhvalov approved these changes

2023-03-16 14:05 UTC, ArkadiySamokhvalov commented on packages/client/src/Store/store.ts
>  import userSlice from '../components/Autification/slice';
Думаю, стоит одинаково называть, чтобы единообразно было. Или Reducer или Slice.

2023-03-16 14:45 UTC, Antidods approved these changes

2023-03-16 18:36 UTC, Zimer-D commented on packages/client/src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
Persist позволяет сохранять данные редакса, например в local storage, т.е. при обновлении страницы не теряются данные

2023-03-17 06:34 UTC, Olegas commented on packages/client/src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
А как это будет дружить с серверным рендерингом приложения? Как будут соединяться состояния, полученные на сервере и сохраненное на клиенте? Этот модуль вообще на сервере сможет работать?

2023-03-17 06:40 UTC, Zimer-D commented on packages/client/src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
В линеаре есть базовая задача(добавленная не командой, а создателями курса) "Добавить возможность сохранять текущее состояние игры (persist state) Для этого вы можете использовать localStorage.  или попробовать огранизовать это сохранение на сервере". Добавление данной библиотеки решает данную задачу через localstorage. На данном этапе при рендере на клиенте это решение функционирует

2023-03-17 06:43 UTC, Olegas commented on packages/client/src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
Ок, понял. Давайте только тесты поправим что бы были не красные и я апрувну

2023-03-17 06:43 UTC, Zimer-D commented on packages/client/src/Store/store.ts
>  import userSlice from '../components/Autification/slice';
ок, поправлю при возможности

2023-03-17 06:48 UTC, Zimer-D commented on packages/client/src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
Возможно, при использовании node.js будем использовать другую технологию, например: https://github.com/odensc/redux-persist-storage-node

2023-03-17 13:22 UTC, Tarakann119 commented on packages/client/src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
Поправил тесты

2023-03-18 04:46 UTC, Olegas approved these changes

2023-03-18 06:58 UTC, merged