Development
Tarakann119/noLabel-game pull request #25
Opened 2023-03-16 14:43 UTC by tamerlan2451

добавлена возможность выбора башен
добавлен фулл скрин web api
пофикшены баги и лаги
добавлен и оптимизирован спрайт башни лучника 
добавлена и переработана карта полностью

2023-03-16 15:32 UTC, Zimer-D approved these changes

2023-03-16 15:34 UTC, tmj1 approved these changes

2023-03-16 17:06 UTC, ArkadiySamokhvalov approved these changes

2023-03-18 07:26 UTC, Olegas requested changes

2023-03-18 07:26 UTC, Olegas commented on packages/client/src/components/Canvas/index.tsx
> +    const fullscreenButton = document.querySelector('.fullscreen');
Не очень правильно так делать. Лучше бы сделать компонент где будет переключатель фулскрина и у него слушать событие, далее по событию менять какой-то пропс у компонента канваса и на него уже реагировать

2023-03-18 07:26 UTC, Olegas commented on packages/client/src/components/Title/index.scss
> +@import "../../assets/styles/varThemeDefault";
Кавычки поменялись. Все же у вас в проекте двойные или одинарные? судя по остальному коду - одинарные

2023-03-18 07:26 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        canvas.addEventListener('mouseup', () => this.myUp());
Вот у вас появился код подписки на события у canvas. Но игра же не вечная у вас? Пользователь может перейти на соседнюю страницу и игра по идее должна как-то "разрушиться" и снять обработчики, убрать ссылки на canvas из своих свойств. Если этого не сделать - будут утечки памяти.

2023-03-18 07:26 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        if (symbol === 91448) {
Тут бы константу какую-то, а то совсем не понятно что это за число такое

2023-03-18 07:26 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        (towers[i].isDragging = false);
А зачем тут несколько операций через ,? Почему просто отдельными строками через ; не написать?

2023-03-18 07:26 UTC, Olegas commented on packages/client/typings/app.typings.ts
> +export type TowerList = {
Это наверное все же не List а просто Tower?

2023-03-19 18:46 UTC, Olegas requested changes

2023-03-19 18:46 UTC, Olegas commented on packages/client/src/components/Canvas/index.tsx
> +        new Game(canvas, props.mapName).removeAllEvents();
Вы создаете новый экземпляр игры. Все отписки не будут иметь смысла ведь они будут отписывать другие функции

2023-03-19 18:46 UTC, Olegas commented on packages/client/src/game/Game.ts
> +    canvas.removeEventListener('click', () => this.handleClickEvent);
Эта отписка не сработает, потому что здесь каждый раз создается новая функция. Подписываете одну, отписываете другую

2023-03-19 18:46 UTC, Olegas commented on packages/client/src/game/Game.ts
> +    canvas.removeEventListener('mouseup', this.myUpEvent);
Для сравнения вот тут - правильно

2023-03-19 18:46 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +    const fullscreenButton = document.querySelector('.fullscreen');
Я кажется писал замечание к этой строчке... Вы обращаетесь к верстке, которую сами не строите (ее строит какой-то другой компонент). Не надо так. Пусть у вас компоненты общаются как-то, через родительский компонент или через стор. Но не надо вешать события на чужие DOM-элементы

2023-03-21 11:56 UTC, Olegas requested changes

2023-03-21 11:56 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        canvas.addEventListener('click', this.handleClickEvent(coins));
И снова проблема. Подписали одно, отписываете потом другое. Зачем тут доступ к coins? Обработчик с экземпляра класса не может его получить?

2023-03-21 11:56 UTC, Olegas commented on packages/client/src/game/Game.ts
> +    canvas.removeEventListener('click', this.handleClickEvent as unknown as () => void);
Не то отписываете опять. Не даром пришлось делать каст типов. Потому что он не сходился и пришлось костылять.

2023-03-21 12:05 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        canvas.addEventListener('click', this.handleClickEvent(coins));
Я возможно не донес проблему. Смотрите, у вас есть подписка и отписка от события. При подписке и отписке должна использоваться ровно одна и та же функция. То есть не просто выглядящая так же, а буквально одно и то же значение. Если при подписке у вас сделано addEventListener('click', () => this.smth()) и при отписке () => this.smth() это две разные функции, пусть они даже и делают одно и то же.

2023-03-22 05:42 UTC, Olegas approved these changes

2023-03-22 08:01 UTC, merged