Добавлены тесты
Tarakann119/noLabel-game pull request #26
Opened 2023-03-16 15:08 UTC by tmj1

### Какую задачу решаем
Добавлены тесты

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-16 15:14 UTC, Antidods requested changes

2023-03-16 15:14 UTC, Antidods commented on packages/client/src/components/Button/index.scss
А зачем это изменение?

2023-03-16 15:14 UTC, Antidods commented on packages/client/package.json
Нужно использовать фиксированные версии зависимостей

2023-03-16 15:14 UTC, Antidods commented on packages/client/src/components/Title/index.tsx
Тут просто форматирование?

2023-03-16 15:16 UTC, tmj1 commented on packages/client/src/components/Title/index.tsx
да

2023-03-16 15:30 UTC, Antidods commented on yarn.lock
В след раз не добавляй этот файл в коммит

2023-03-16 15:31 UTC, Antidods commented on packages/client/package.json
> +    "@testing-library/jest-dom": "^5.16.5",
Нужно использовать фиксированные версии зависимостей, а то нас на ревью разнесут

2023-03-16 15:31 UTC, tmj1 commented on packages/client/package.json
> +    "@testing-library/jest-dom": "^5.16.5",
верно

2023-03-16 15:33 UTC, Zimer-D approved these changes

2023-03-16 18:52 UTC, ArkadiySamokhvalov commented on package.json
> +    "@testing-library/react": "^14.0.0"
Этот пакет уже есть в client/package.json. 
Пакеты стоит добавлять в части где они используются в client и/или server. В корневом package.json по идее лежит то что используется для общей настройки.

2023-03-16 18:52 UTC, ArkadiySamokhvalov commented on packages/client/src/components/Input/Input.test.tsx
> +  it('Correctly renders in the DOM', () => {
Просто мнение. 
Я бы описания писал на русском, у нас ведь РУ проект, так просто понятнее.

2023-03-17 07:24 UTC, tmj1 commented on packages/client/src/components/Input/Input.test.tsx
> +  it('Correctly renders in the DOM', () => {
Возможно. Могу поменять. Просто эта часть относится более к "служебной информации", поэтому добавила текст на английском.

2023-03-17 08:13 UTC, tamerlan2451 approved these changes

2023-03-18 04:47 UTC, Olegas approved these changes

2023-03-18 07:20 UTC, merged