AboutUs
Tarakann119/noLabel-game pull request #35
Opened 2023-03-22 21:34 UTC by Antidods

## Добавлена страница "О нас"
Так же сделана небольшая уборка в assets
Проверьте свои данные!!!
***
![image](https://user-images.githubusercontent.com/100022449/227042860-57bde148-d4d5-452b-afe9-5c7956affdf0.png)

2023-03-23 08:51 UTC, ArkadiySamokhvalov approved these changes

2023-03-23 15:02 UTC, tmj1 approved these changes

2023-03-23 17:45 UTC, Olegas requested changes

2023-03-23 17:45 UTC, Olegas commented on packages/client/src/ui/AuthorItem/index.tsx
> +      <ButtonImg variant={item.type} onClick={() => window.open(item.url)} style={{ margin: 10 }} />
При создании компонентов из итератора нужно каждому не забыть назначить ключ (свойство key)

2023-03-23 17:45 UTC, Olegas commented on packages/client/src/ui/AuthorItem/index.tsx
> +      <span className=''> {text} </span>
Тут лишние пробелы и пустой класс

2023-03-24 06:17 UTC, Antidods commented on packages/client/src/ui/AuthorItem/index.tsx
> +      <ButtonImg variant={item.type} onClick={() => window.open(item.url)} style={{ margin: 10 }} />
Исправил, спасибо что указали на ошибку.

2023-03-24 06:18 UTC, Antidods commented on packages/client/src/ui/AuthorItem/index.tsx
> +      <span className=''> {text} </span>
Исправил.

2023-03-25 06:12 UTC, Olegas commented on packages/client/src/ui/AuthorItem/index.tsx
> +        key={uuid()}
Так тоже можно, но достаточно что бы была просто какая-то любая уникальная строка. В вашем случае было бы достаточно item.url

2023-03-25 06:12 UTC, Olegas approved these changes

2023-03-25 08:12 UTC, merged