Добавление звука
Tarakann119/noLabel-game pull request #37
Opened 2023-03-23 20:48 UTC by tmj1

### Какую задачу решаем
Добавлен звук

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-24 04:35 UTC, Zimer-D commented on package.json
> +    "use-sound": "^4.0.1"
зафиксисируй версию зависимости

2023-03-24 04:37 UTC, Zimer-D commented on packages/client/src/pages/LoginPage/index.tsx
> +            <Button text='Вход' type='submit' className='custom-button' onMouseUp={randomClickSound} />
Тип кнопки надо поменять. submit отвечает за формы, если этого не сделать - форма сойдет с ума

2023-03-26 15:02 UTC, Antidods commented
@tmj1 папка с МР3 не загрузилась
![image](https://user-images.githubusercontent.com/100022449/227784549-0162cea4-dd8e-407a-8359-26b54194c709.png)

2023-03-26 16:28 UTC, Antidods requested changes
Ошибки типизации в компонентах: Controls, DisplayTrack, ProgressBar. Продакшн сборка не работает:
![image](https://user-images.githubusercontent.com/100022449/227789065-28f69c92-bee8-4c96-a47c-f4e147a2d16c.png)
Так же перед merge с development нужно стилизовать footer:
![image](https://user-images.githubusercontent.com/100022449/227789867-4f8373c2-6eea-4ebd-840b-54e15fc32aac.png)

2023-03-27 07:18 UTC, Zimer-D requested changes
нужна типизация

2023-04-04 20:14 UTC, Antidods commented
@tmj1 сорян, походу во время резолва конфликтов снес импорт функции добавления рандомных звуков - поправь пожалуйста, как будет возможность. Так-же обрати внимание что ты создала компонент Link и в него импортировала функцию с рандомными звуками, но сам компонент Link в проекте нигде не используется. Так же я бы упаковал все части аудиоплеера в один каталог.

2023-04-04 20:25 UTC, tamerlan2451 approved these changes

2023-04-05 09:49 UTC, ArkadiySamokhvalov commented
Я до сих пор не понимаю зачем это нужно. 
Музыка играющая во время игры и звуки при нажатии на кнопках в ней же ещё понятны. А на всех страницах зачем? 
Я такого не видел на других сайтах посвященных играм, это в целом неожиданное поведение.  
Собственно на странице с игрой это всё работает не совсем корректно.  Музыка играет отдельно  - не синхронизируется с началом/концом игры. И я так понял что звуки при нажатии на кнопки рандомные? Получается все кнопки в меню будут звучать по разному. 
Я считаю, что как опыт - это всё здорово. Но в таком виде подключать в проект - идея плохая.

2023-04-05 13:34 UTC, ArkadiySamokhvalov commented
Я предлагаю убрать компонент со страниц и убрать его верстку. 
Вижу, что поставлен [use-sound](https://www.npmjs.com/package/use-sound), но не вижу чтобы он использовался.  
Поскольку вся логика работы написана самостоятельно. Можно убрать пакет use-sound и доделать свой код до аналога, т.е. сделать свой [кастомный хук](https://ru.reactjs.org/docs/hooks-custom.html).

Чтобы можно было вызвать его в необходимых компонентах, например:
```
import song1 from './songs/song1.mp3';
import song2 from './songs/song2.mp3';

export const Component = () => {
  const [play, stop, changeSong, changeVolume] = useSound(song1);

 ...
}
```
play() - запускает песню
stop() - ставит на паузу
changeSong(song) - меняет песню на переданную
changeVolume() - уменьш/увелич звук на 1ед
turnOffVolume() - вкл/выкл звук совсем / можно объединить с changeVolume

2023-04-09 17:14 UTC, tmj1 commented
> 

исправлено.

2023-04-09 17:16 UTC, tmj1 commented
> Я предлагаю убрать компонент со страниц и убрать его верстку. Вижу, что поставлен [use-sound](https://www.npmjs.com/package/use-sound), но не вижу чтобы он использовался. Поскольку вся логика работы написана самостоятельно. Можно убрать пакет use-sound и доделать свой код до аналога, т.е. сделать свой [кастомный хук](https://ru.reactjs.org/docs/hooks-custom.html).
> 
> Чтобы можно было вызвать его в необходимых компонентах, например:
> 
> ```
> import song1 from './songs/song1.mp3';
> import song2 from './songs/song2.mp3';
> 
> export const Component = () => {
>   const [play, stop, changeSong, changeVolume] = useSound(song1);
> 
>  ...
> }
> ```
> 
> play() - запускает песню stop() - ставит на паузу changeSong(song) - меняет песню на переданную changeVolume() - уменьш/увелич звук на 1ед turnOffVolume() - вкл/выкл звук совсем / можно объединить с changeVolume

уже примерно так и реализовано в компоненте Controls. Можно убрать с футера и соответственно добавить только на страницу игры.

2023-04-10 18:07 UTC, ArkadiySamokhvalov approved these changes

2023-04-10 18:07 UTC, Zimer-D approved these changes

2023-04-10 18:07 UTC, Antidods approved these changes

2023-04-10 19:03 UTC, Olegas commented on packages/client/src/components/DisplayTrack/index.tsx
> +    progressBarRef.current.max = seconds.toString();
Тут что-то не так... Какая-то путаница. Компонент называется Display но он не еще содержит сам тэк audio и еще знает о каком-то прогрессбаре хотя вроде как не понятно почему он сраружи, ведь это как раз и есть display? А в итоге прогрессбар где-то в controls которые показывают прогресс (не понятно) и управляют воспроизведением (понятно). 
Что если плеер вынести наружу относительно display и controls? Кажется так будет пряммее. Плеер згразил трек, всю информацию отдал в display для отображения, слушает события от controls. И кажется даже ref-ы через все компоненты не надо будет передавать

2023-04-10 19:04 UTC, Olegas commented on packages/client/src/components/ProgressBar/index.scss
Пустой файл

2023-04-17 19:42 UTC, tmj1 commented on packages/client/src/components/AudioPlayer/index.tsx
> +      setCurrentTrack(tracks[0]);
Код переработан

2023-04-17 19:43 UTC, tmj1 commented on packages/client/src/components/DisplayTrack/index.tsx
> +    progressBarRef.current.max = seconds.toString();
данный файл удален в связи с переосмыслением функционала

2023-04-17 19:43 UTC, tmj1 commented on packages/client/src/components/ProgressBar/index.scss
удален файл

2023-04-18 05:37 UTC, Olegas requested changes

2023-04-18 05:37 UTC, Olegas commented on packages/client/src/components/Footer/index.tsx
> +          {AudioPlayer()}
Почему плеер так странно вставляется? Почему не просто <AudioPlayer />?

2023-04-18 05:37 UTC, Olegas commented on packages/client/src/components/Link/index.tsx
> +        return randomClickSound;
А вот тут не забыли функцию позвать? Кажется сейчас вы просто ввернете из обработчика клика функцию, и она не будет ни кем вызвана

2023-04-18 08:26 UTC, tmj1 commented on packages/client/src/components/Footer/index.tsx
> +          {AudioPlayer()}
впоследствие будет вставлен на правильные места в самой игре. доработки по игре еще ведутся

2023-04-18 08:28 UTC, tmj1 commented on packages/client/src/components/Link/index.tsx
> +        return randomClickSound;
данный компонент не ислользуется - удален

2023-04-18 18:07 UTC, Olegas commented on packages/client/src/components/Footer/index.tsx
> +          {AudioPlayer()}
Ох, я только сейчас заметил что в комментарии пропала разметка. Я писал "Почему не просто `<AudioPlayer />`"

2023-04-18 18:08 UTC, Olegas approved these changes

2023-04-24 06:10 UTC, merged