API Leaderboard
Tarakann119/noLabel-game pull request #39
Opened 2023-03-26 14:39 UTC by Antidods

## Добавлен API таблицы лидеров

***
Запросы к API для актуализации таблицы лидеров выполняются при посещении страниц leaderboard и profile.
Запрос на добавление данных в таблицу лидеров происходит после окончания игры. Стоит отметить, что запрос выполняется даже если игрок набрал меньшее количество очков, чем в предыдущий раз. Это сделано намерено, т.к. пользователь мог сменит свои учётные данные и необходимо их актуализировать в leaderboard. 

Так же, как выяснилось, API Яндекса отдаёт данные leaderboard только при валидных cookie, поэтому роут Leaderboard был перемещён в RequireAuth. Так же была изменена стартовая страница, теперь для незалогиненного пользователя стартовая страница выглядит так:
![image](https://user-images.githubusercontent.com/100022449/227781616-a0aa0ccb-dcb5-4af3-90f6-f6259adbf7a1.png)

Все запросы к API выполняются дважды, почему так происходит - я на данный момент не понимаю
![image](https://user-images.githubusercontent.com/100022449/227777098-234dcf60-68ac-4a44-ae7b-e2ae039cc212.png)

Потребление памяти, после добавления API для лидерборда, возросло, с 9.7mb до 11.4mb в пике.
![image](https://user-images.githubusercontent.com/100022449/227778943-3f13eb86-5d54-44b6-bafa-d87424a8bcc4.png)

Утечек памяти нет, после сборки мусора, объём занятой памяти опускается до изначального значения.
![image](https://user-images.githubusercontent.com/100022449/227779441-cdb8efad-bbf4-4a36-8bb5-d941adec6563.png)

2023-03-26 15:29 UTC, tmj1 approved these changes

2023-03-27 04:10 UTC, Zimer-D requested changes

2023-03-27 04:10 UTC, Zimer-D commented on packages/client/src/components/Leaderboard/slice.ts
> +        console.log(response);
консоль лог наверное стоит убрать

2023-03-28 19:04 UTC, Antidods commented
@Olegas StrictMode был включен и после его отключения всё стало ок. 
Большое спасибо!
![image](https://user-images.githubusercontent.com/100022449/228341412-a88e7049-e738-4dcb-8d80-74d29cbc51ad.png)

2023-03-28 19:08 UTC, Olegas requested changes

2023-03-28 19:08 UTC, Olegas commented on packages/client/src/components/Leaderboard/slice.ts
> +          order++;
Если вам нужен порядковый номер элемента при переборе, он есть во втором аргументе в вашей функции `.map((item, index) => ...`

2023-03-28 19:08 UTC, Olegas commented on packages/client/src/pages/Leaderboard/index.tsx
> +  } else return <div className='container-content bg-image_login container_start'></div>;
В конце функции можно не делать else, ведь тут сразу return и далее нет ничего.

2023-03-28 19:10 UTC, Olegas commented
> StrictMode был включен и после его отключения всё стало ок.

На самом деле это полезная для разработки штука - она позволяет проверить, что у вас сайд эффекты корректные. При включенном strict mode React по сути делает рендеринг дважды каждый раз. Это позволяет выявить некоторые ошибки, можно почитать об этом в документации.
При продакшен-сборке strict mode атвоматически выключается

2023-03-29 11:29 UTC, ArkadiySamokhvalov approved these changes

2023-03-29 20:33 UTC, Antidods commented on packages/client/src/components/GameField/index.tsx
> +    );
Исправил

2023-03-29 20:33 UTC, Antidods commented on packages/client/src/components/Leaderboard/index.tsx
> +import { getDataForLeaderBoard, leaderboard } from '@store/selectors';
переименовал селектор

2023-03-29 20:33 UTC, Antidods commented on packages/client/src/components/Leaderboard/index.tsx
> +  const userScore = leaderboardList.find((el) => el.id === currUser.id) as LeaderboardUserType;
убрал в отдельный селектор

2023-03-29 20:56 UTC, Antidods commented on packages/client/src/components/Leaderboard/slice.ts
> +      state.totalGamers = state.leaderboard.length;
Удалил setLeaderboard, он стал не нужен после добавления extraReducers

2023-03-29 20:57 UTC, Antidods commented on packages/client/src/components/Leaderboard/slice.ts
> +          order++;
Спасибо, совсем забыл про второй аргумент.

2023-03-29 20:58 UTC, Antidods commented on packages/client/src/components/Leaderboard/slice.ts
> +        thunkAPI.dispatch(setLeaderboard(leaderboardList));
Переписал всё на extraReducers

2023-03-29 20:58 UTC, Antidods commented on packages/client/src/pages/Leaderboard/index.tsx
> +        },
Исправил

2023-03-29 20:59 UTC, Antidods commented on packages/client/src/pages/Leaderboard/index.tsx
> +  } else return <div className='container-content bg-image_login container_start'></div>;
Исправил

2023-03-29 21:03 UTC, Antidods commented
@Olegas спасибо за объёмное ревью. Исправил все замечания, добавил extraReducers.

2023-03-29 21:06 UTC, Antidods commented
![image](https://user-images.githubusercontent.com/100022449/228667131-cbb118ac-aa6a-4be0-bcb8-d1fa9aed5898.png)
## Актуальный state

2023-03-30 05:28 UTC, Olegas requested changes

2023-03-30 05:28 UTC, Olegas commented on packages/client/src/pages/Leaderboard/index.tsx
> +    const currUser = useSelector(getDataForLeaderBoard);
Внимание! Грубая ошибка! Хуки нельзя убирать под условие. Все хуки должны выполняться при каждом рендере компонента

2023-03-30 05:28 UTC, Olegas commented on packages/client/src/pages/Profile/index.tsx
> +  }, [dispatch]);
А для чего это здесь? Вроде дальше на этой странице не используется...

2023-03-30 05:28 UTC, Olegas commented on packages/client/src/components/GameField/index.tsx
> +        points && pushScore(points);
А вот эти два диспатча нельзя в одной действие объединить? То есть с точки зрения игры мы записываем результат. Дальше внутри экшена он идет на сервер и куда-то еще в стейт

2023-03-30 05:29 UTC, Olegas commented
> ## Актуальный state

А для чего отдельный признак authState? Может его расчетным сделать? Если заполнен auth.user то authState = true (сделать селектор для этого)

2023-03-30 07:27 UTC, Antidods commented
@Olegas соответствующие изменения внесены. Касаемо authState: для получения расчётного значения авторизации у нас есть хук useAuth, но я хотел состояние авторизации вынести в отдельный признак и как раз его сделать управляющим + в каждый сетевой запрос добавить условия, что если запрос отклоняется с 401 кодом - изменяется состояние useAuth и слетают данные юзера и лидерборда. Что скажете?

2023-03-30 11:47 UTC, Antidods commented on packages/client/src/pages/Profile/index.tsx
> +  }, [dispatch]);
Вы совершенно правы, на этой странице не используется, но после успешного логина мы попадаем на страницу профиля, так что данные лидерборда гарантированно будут загружены. Далее мы актуализируем данные лидерборда каждый раз при посещении страницы Рейтинг и после отправки данных лидерборда.

2023-03-30 11:47 UTC, Antidods commented on packages/client/src/components/GameField/index.tsx
> +        points && pushScore(points);
С вашего позволения, хотел бы оставить так, setPoints писал не я, а мы в команде стараемся не трогать чужой код без особой необходимости.

2023-03-30 11:49 UTC, Antidods commented on packages/client/src/components/GameField/index.tsx
> +    dispatch(pushUserScore({ user: user, score: score }));
Переделал, теперь pushUserScore принимает 1 параметр

2023-03-30 11:50 UTC, Antidods commented on packages/client/src/pages/Leaderboard/index.tsx
> +    const currUser = useSelector(getDataForLeaderBoard);
Исправил

2023-03-30 18:39 UTC, Olegas commented on packages/client/src/components/GameField/index.tsx
> +        points && pushScore(points);
Ок, давайте оставим. Но в команде не должно быть понятия "чужой код". Нет никакого моего и чужого кода. Ни к чему хорошему обычно такое не приводит.

2023-03-30 18:42 UTC, Olegas requested changes

2023-03-30 18:42 UTC, Olegas commented on packages/client/src/components/Leaderboard/slice.ts
> +      const user = thunkAPI.dispatch(currentUser);
Стоп, как это dispatch? currentUser это же селектор.

2023-03-30 19:17 UTC, Antidods commented on packages/client/src/pages/Profile/index.tsx
> +  }, [dispatch]);
Эти же данные используются на стартовой, но добавлять запрос к API на стартовую страницу не  стал для ускорения загрузки, т.к. на данный момент в проекте отсутствует SSR, а на странице профиля уже и так есть запрос к API. Если логика неверная - скажите и я всё переделаю.

2023-03-30 19:37 UTC, Antidods commented on packages/client/src/components/Leaderboard/slice.ts
> +      const user = thunkAPI.dispatch(currentUser);
@Olegas  прошу прощения за глупый вопрос, а как тогда получить данные из селектора в слайсе?

2023-03-30 19:40 UTC, Antidods commented
> > @Olegas соответствующие изменения внесены. Касаемо authState: для получения расчётного значения авторизации у нас есть хук useAuth, но я хотел состояние авторизации вынести в отдельный признак и как раз его сделать управляющим + в каждый сетевой запрос добавить условия, что если запрос отклоняется с 401 кодом - изменяется состояние useAuth и слетают данные юзера и лидерборда. Что скажете?
> 
> Это все очень хорошо, но не понятно зачем отдельный флаг держать. Почему нельзя просто смотреть - есть или нет user в стейте? При разлогине или ошибке - чистить его.

Месседж принял, флаг удалил
![image](https://user-images.githubusercontent.com/100022449/228946179-76ff9048-7718-4df8-80fe-7c77bedf8e23.png)

2023-03-30 20:13 UTC, Antidods commented on packages/client/src/components/Leaderboard/slice.ts
> +      const user = thunkAPI.dispatch(currentUser);
`const user = currentUser(thunkAPI.getState());` Так можно?

2023-04-01 06:47 UTC, Olegas commented on packages/client/src/components/Leaderboard/slice.ts
> +      const user = thunkAPI.dispatch(currentUser);
Да, именно так

2023-04-02 07:59 UTC, Antidods commented
@Olegas , если больше нет замечаний - заапрувьте пожалуйста.

2023-04-02 15:11 UTC, Olegas approved these changes

2023-04-03 22:14 UTC, tamerlan2451 approved these changes

2023-04-04 11:49 UTC, merged