23NL-40 авторизация по токену
Tarakann119/noLabel-game pull request #44
Opened 2023-04-06 11:19 UTC by Zimer-D

23NL-40 авторизация по токену

2023-04-06 12:28 UTC, ArkadiySamokhvalov approved these changes

2023-04-06 13:19 UTC, tamerlan2451 approved these changes

2023-04-06 15:10 UTC, Antidods approved these changes

2023-04-07 13:47 UTC, Olegas requested changes

2023-04-07 13:47 UTC, Olegas commented on packages/client/src/components/Autification/slice.ts
> +      data: { code: code, redirect_uri: 'http://localhost:3000/' },
Выше для redirect_uri есть константа, надо ее использовать

2023-04-07 14:01 UTC, Olegas approved these changes

2023-04-07 14:32 UTC, merged