23NL-37: Server Side Rendering
Tarakann119/noLabel-game pull request #46
Opened 2023-04-06 14:16 UTC by tamerlan2451

23NL-09 настройка ssr
23NL-39 настройка redux + srr
ssr + react-router

2023-04-06 14:41 UTC, Antidods approved these changes

2023-04-06 15:42 UTC, ArkadiySamokhvalov commented on packages/client/package.json
> +    "@emotion/server": "^11.10.0",
Не зафиксированы версии.

2023-04-07 13:35 UTC, Olegas requested changes

2023-04-07 13:35 UTC, Olegas commented on packages/client/src/components/Theme/slice.ts
> +  if (typeof window === 'undefined') {
Получается если пользователь переключит тему и перезагрузит страницу, то ему прилетит светлый вариант и затем на клиенте перерисуется на темную?

2023-04-08 00:33 UTC, tamerlan2451 commented on packages/client/src/components/Theme/slice.ts
> +  if (typeof window === 'undefined') {
проблема как раз таки и в том что стили на сервер вообще не приходят , о чем я и пишу в пачке

2023-04-08 06:53 UTC, Olegas commented on packages/client/src/components/Theme/slice.ts
> +  if (typeof window === 'undefined') {
Ну почему они не приходят я в пачке ответил - вы используете библиотеку, которая работает с css-in-js но сам этот подход не используете. Надо иначе извлекать стили, соответственно вашему варианту их написания.

После того как проблема со стилями будет решена - появится проблема о которой я пишу здесь

2023-04-10 18:20 UTC, ArkadiySamokhvalov approved these changes

2023-04-10 18:50 UTC, Olegas requested changes

2023-04-10 18:50 UTC, Olegas commented on packages/client/server.js
> +      const cssFile = files.find(file => path.extname(file) === '.css');
А файл точно всегда один?

2023-04-10 18:50 UTC, Olegas commented on packages/client/package.json
> +    "@emotion/server": "^11.10.0",
Вы не используете emotion. Он тут точно еще нужен?

2023-04-10 18:50 UTC, Olegas commented on packages/client/server.js
> +        .replace(`<!--css-->`, `<style>${css}</style>`)
Если CSS не загрузили, тут получится <style>undefined</style>

2023-04-10 18:50 UTC, Olegas commented on packages/client/index.html
> +  <script type="module" src="/src/entry-client.tsx"></script>
В продакшен-режиме это точно не заработает. Браузер не умеет обрабатывать typescript-файлы. Посмотрите вебинары по SSR чтобы сделать правильно. Там разобран рабочий вариант

2023-04-10 19:21 UTC, tamerlan2451 commented on packages/client/server.js
> +      const cssFile = files.find(file => path.extname(file) === '.css');
я не сразу понял насколько это хороший вариант , если все css файлы объединить и запулить туда , от 1 до 10 насколько этот вариант хороший ? бест практик не хватает, в инете один только css in js , а обычные css или scss которые у всех компонентов импортируются отдельно, т.е у всех компонентов свой scss файлик . много библиотек затаскивал , все не дали нужного результата , либо не сумел правильно ими оперировать . 

и вопрос , почему линки у сбилженного index.html не работают , там есть линк на подключение css файлика которого я тут и находил . он не реагирует если оставить как есть .

впрочем , я вебинары проморгал , не заметил их . надеюсь они прояснят ситуацию

2023-04-14 18:53 UTC, Olegas commented on packages/client/server.js
> +      const cssFile = files.find(file => path.extname(file) === '.css');
Извиняюсь. Не заметил правильное решение на 8 строке.

2023-04-14 18:53 UTC, Olegas approved these changes

2023-04-14 21:08 UTC, tamerlan2451 commented on packages/client/src/components/Autification/slice.ts
> +export const userReducer = createSlice({
экспорт убрать забыл , в следующих коммитах уберу

2023-04-14 21:09 UTC, tamerlan2451 commented on packages/client/src/App.tsx
> +      dispatch(fetchLeaderboard());
вместе 'done' хотел написать 'init', так будет правильнее, это тоже поменяю

2023-04-19 13:35 UTC, merged