23NL-47 Настройте PostgreSQL / 23NL-87-88 Cерверная часть API
Tarakann119/noLabel-game pull request #48
Opened 2023-04-15 11:14 UTC by Antidods

## Настроена PostgeSQL, разработана серверная часть API форума и лидерборда.

ENV не настроено под продакшн, так что пока запускаем сервер в dev режиме.
Обратите внимание, перед запуском dev сервера нужно запустить контейнер с БД командой:
```
docker compose up postgres
```
При первом запуске контейнера с postgres необходимо создать каталог tmp/pgdata, выполнив:
```
node init.js
```
Для удобства тестирования могу предложить volume с БД, в которой набито немного тестовых данных
[https://disk.yandex.ru/d/xyOO53iGyPW_ww](url)

Так же в папке с API есть json с запросами для postman и README с кратким описанием всех ручек.

Функционал ручек не окончательный, по ходу написания фронта возможно придётся что то добавить.

Схема БД выглядит примерно так:
![image](https://user-images.githubusercontent.com/100022449/232210485-dcb84784-3665-4263-8270-f2ceb8eee075.png)

2023-04-17 18:16 UTC, Zimer-D approved these changes

2023-04-17 18:21 UTC, tamerlan2451 approved these changes

2023-04-18 05:47 UTC, Olegas commented
1. У вас падают тесты (Lint) - поправьте пожалуйста
2. Замечания к схема БД: 
  1. Неконсистентность в именовании - Forum_topics единственная таблица с названием во множественном числе, надо сделать одинаково
  2. Еще одна неконсистентность в именовании ссылок. Например в т. Emoji ссылка на пользователя - user_id, а на сообщение просто message (без _id)
  3. Ссылка на автора в одном месте id_author, в другом author_id - надо сделать одинаково
  4. Где-то PK называется id (нормально), где-то иначе (например user_id в таблице User) - лучше одинаково, id
  5. Для чего таблица Leaderboard? Разве это не в API Яндекса хранится
  6. Зачем одновременно поле author_id и author (т. Emoji)?

2023-04-18 05:59 UTC, Olegas requested changes
Дополнительное замечание (не стал писать под строчками): там, гле вы осуществляете поиск модели по каким-то параметрам (например эмодзи по ид сообщения) - нужно сделать индексы. Их сейчас нет нигде.
Два места которые индексируются автоматически - Primary ключи и колонки с Unique. Остальное надо писать явно

2023-04-18 05:59 UTC, Olegas commented on packages/client/index.html
> +  </body>
Какое отношение изменение кавычек имеет к выполняемой задаче? Почему вообще они опять меняются?

2023-04-18 05:59 UTC, Olegas commented on packages/server/API/controllers/emojiController.ts
> +    const user = await User.findByPk(req.body.author);
А вы уже проверяете сами авторизацию или еще нет? Если да то может автора брать из нее а не передавать с клиента?

2023-04-18 05:59 UTC, Olegas commented on packages/server/API/models/User.ts
> +  @Unique
Primary key уже уникальный, не надо отдельно

2023-04-18 05:59 UTC, Olegas commented on packages/server/API/models/User.ts
> +  @Column(DataType.INTEGER)
А вот эта колонка действительно должна быть уникальной

2023-04-18 05:59 UTC, Olegas commented on packages/server/API/models/User.ts
> +  login?: string;
И эта уникальная

2023-04-18 05:59 UTC, Olegas commented on packages/server/API/models/User.ts
> +  email?: string;
И эта уникальная

2023-04-18 05:59 UTC, Olegas commented on packages/server/API/models/User.ts
> +  phone?: string;
И эта уникальная

2023-04-18 05:59 UTC, Olegas commented on packages/server/utils/regExp/XSS.ts
> +export const SQLRegExp = /(['"])(?:(?=(\\?))\2.)*?\1/g;
А зачем это? У вас же ORM, вы же явно значения параметров в запросы не подставляете.

2023-04-18 15:40 UTC, Antidods commented on packages/server/API/controllers/emojiController.ts
> +    const user = await User.findByPk(req.body.author);
На данный момент прокси ещё не готов и да, мы планируем брать данные пользователя с API Практикума и закидывать в базу.

2023-04-18 15:41 UTC, Antidods commented on packages/server/API/models/User.ts
> +  @Unique
Поправил

2023-04-18 15:47 UTC, Antidods commented on packages/server/utils/regExp/XSS.ts
> +export const SQLRegExp = /(['"])(?:(?=(\\?))\2.)*?\1/g;
Побоялся что при подставление ORMкой значений в sql запросы, можно будет вкинуть инъекцию.

2023-04-18 16:19 UTC, Antidods commented on packages/server/utils/regExp/XSS.ts
> +export const SQLRegExp = /(['"])(?:(?=(\\?))\2.)*?\1/g;
@Olegas спасибо за ревью! Все замечания устранил, но есть пару вопросов:

1.  ![image](https://user-images.githubusercontent.com/100022449/232833187-1e7af72d-6a9e-4c7c-8f04-30908891c096.png) Так правильно?
2. После добавления индекса, меняется ли алгоритм поиска или как и раньше можно искать по названию столбца?![image](https://user-images.githubusercontent.com/100022449/232834206-146bd208-577c-4b9f-836c-d463ae48a25c.png)
3. Хотелось бы в ответ контроллера getAllForumTopics добавить поле last_message, в котором была бы информация о последнем сообщении. Сейчас на выдаче контроллера я получаю массив тем форума и в каждой теме лежит массив всех сообщений темы, что в корне не правильно. Можно ли как то силами ORM из массива сообщений достать последнее? Я пробовал сделать это следующим способом: добавить в include сортировку по дате и установить оффсет в 1 элемент. По отдельности это всё работает, т.е. при добавлении сортировки получаю массив отсортированный по дате, при добавлении оффсета получаю один элемент массива, но при добавлении обоих условий - просто получаю первый элемент из неотсортированной таблицы. Я конечно могу в контроллере пробежаться двумя циклами, но хотелось бы разобраться как это можно сделать с помощью ORM 
![image](https://user-images.githubusercontent.com/100022449/232840213-1c917277-f51a-4bf7-83c8-04c22a9b85a1.png)

2023-04-18 16:29 UTC, Antidods commented
По поводу тестов - внезапно линтер начал выкидывать ошибку по файлу, который я даже не трогал в этом ПР.
![image](https://user-images.githubusercontent.com/100022449/232842288-cf6f72f3-c96d-4ecb-8145-b0bea1ac9dfe.png)
при этом в нём явно нет ошибки в импортах, локально все проверки проходят.

2023-04-19 05:58 UTC, Olegas commented on packages/server/utils/regExp/XSS.ts
> +export const SQLRegExp = /(['"])(?:(?=(\\?))\2.)*?\1/g;
> 1. Так правильно?

Да

> 2\. как и раньше можно искать по названию столбца

Алгоритм поиска не меняется, просто работа базы будет быстрее

> 3\. Я конечно могу в контроллере пробежаться двумя циклами, но хотелось бы разобраться как это можно сделать с помощью ORM

Не подскажу, надо смотреть документацию что тут за подводные камни.
Главное не надо делать так что вы из полного списка руками выбираете последний. Лучше какой-то отдельный метод написать который например достанет по одному сообщению из каждой темы

2023-04-21 08:09 UTC, Antidods commented
@Olegas все замечания устранены, кроме контроллера ForumTopics, заапрувь пожалуйста этот ПР, ForumTopics я отдельным кину.

2023-04-21 15:35 UTC, Antidods commented
![image](https://user-images.githubusercontent.com/100022449/233677019-028a7b8c-2c4c-416c-a998-480ce07ae6d1.png)

2023-04-21 15:36 UTC, Olegas approved these changes

2023-04-21 16:12 UTC, merged