23NL-26: Сверстать страницу форума / 23NL-46: Добавьте возможность переключать темы.
Tarakann119/noLabel-game pull request #52
Opened 2023-04-21 23:26 UTC by ArkadiySamokhvalov

### Какую задачу решаем
23NL-26: Сверстать страницу форума.
23NL-46: Добавьте возможность переключать темы.
- Добавлены css переменные

2023-04-22 07:11 UTC, Zimer-D approved these changes

2023-04-22 07:33 UTC, Antidods approved these changes

2023-04-22 15:51 UTC, Olegas commented
Господа, давайте пожалуйста так больше не делать - две задачи в одном PR. В следующий раз я заверну review на доработку и буду смотреть только когда PR будет разбит на два.

2023-04-22 16:13 UTC, Olegas requested changes

2023-04-22 16:13 UTC, Olegas commented on packages/client/src/components/Input/index.tsx
> +      <label className='input__label' htmlFor='login'>
htmlFor не должен тут параметризоваться?

2023-04-22 16:13 UTC, Olegas commented on packages/client/src/components/Input/index.tsx
> +      <div className={classNames('input__wrapper', { 'input__wrapper-error': error })}>
А сам текст ошибки тут не должен выводиться где-то?

2023-04-22 16:13 UTC, Olegas commented on packages/client/src/pages/CreateTopic/index.tsx
> +    <main className={classNames('container-content', 'container-content_main', 'bg-image_login')}>
Когда все классы статичные, можно не использовать classNames, это избыточно

2023-04-22 16:13 UTC, Olegas commented on packages/client/src/pages/Forum/index.tsx
> +import '@/components/Header/index.scss';
А для чего импортируются стили для Header отдельно? Мы разве не должны тут компонент Header использовать? Зачем стили отдельно?

2023-04-22 17:03 UTC, ArkadiySamokhvalov commented on packages/client/src/components/Button/index.scss
> +%button {
Это из scss. Задаётся название и прописываются стили, потом к нему можно обратиться через @extends.
Есть вариант использовать через название класса напрямую @extends .button, но dart-sass рекомендует вынести как переменную( не знаю точно как это называется, но смысл такой).

2023-04-22 17:09 UTC, ArkadiySamokhvalov commented on packages/client/src/components/Input/index.tsx
> +      <label className='input__label' htmlFor='login'>
Посмотрел, этот компонент нигде не используется. Удалил его

2023-04-22 17:21 UTC, ArkadiySamokhvalov commented on packages/client/src/pages/CreateTopic/index.tsx
> +    <main className={classNames('container-content', 'container-content_main', 'bg-image_login')}>
Согласен, убрано

2023-04-22 18:22 UTC, ArkadiySamokhvalov commented on packages/client/src/components/Input/index.tsx
> +      <div className={classNames('input__wrapper', { 'input__wrapper-error': error })}>
Есть компонет InputValidate, там всё необходимое присутствует. А это что-то закралось из старых наработок.

2023-04-22 18:30 UTC, ArkadiySamokhvalov commented on packages/client/src/pages/Forum/index.tsx
> +import '@/components/Header/index.scss';
Убрано

2023-04-23 11:39 UTC, tamerlan2451 approved these changes

2023-04-24 19:58 UTC, Olegas approved these changes

2023-04-25 08:54 UTC, merged