23NL-69
Tarakann119/noLabel-game pull request #54
Opened 2023-04-24 16:35 UTC by tamerlan2451

23NL-69 переработана система постройки башен
23NL-68 добавлены две новые башни

немного переработан баланс

2023-04-24 17:12 UTC, Zimer-D approved these changes

2023-04-24 20:04 UTC, Olegas commented on packages/client/src/game/Game.ts
> +    requestAnimationFrame(animate);
Эту функцию можно порефакторить так, что бы не было копипасты. 
Попробуйте сложить башни в массив в виде объектов, каждый их которых описывает позицию, стоимость и т.п. А затем просто по этому массиву пробегать, сравнивать координаты и в случае совпадения выполнять типовые действия.

2023-04-25 04:23 UTC, Olegas commented on packages/client/src/game/Game.ts
> +    requestAnimationFrame(animate);
Круто что ты думаешь о производительности потому что цикл анимации - действительно важное место. Но если подумать, мы ведь не добавили лишней работы. Будут делаться все те же операции что в цикле что последовательно.

2023-04-25 04:28 UTC, Olegas requested changes

2023-04-25 04:28 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        const towerList = [
Если думать о производительности, то нужно этот массив создать где-то один раз а не на каждом animation frame

2023-04-25 04:28 UTC, Olegas commented on packages/client/src/game/Game.ts
> +            position:
... но position зависит от this и значений на нем 🤔
Тогда надо вынести свойства вида (например) offsetX, offsetY и в них хранить смещения, которые подставить в условие (ведь проверка у всех одинаковая, отличается лишь смещение, верно?

2023-04-25 04:28 UTC, Olegas commented on packages/client/src/game/Game.ts
> +          if (el.position) {
Сам код проверки смещений, зависящий от this.cursor и activeTile.position будет тут, а смещения надо брать из el.position

2023-04-25 04:28 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        towerList.forEach((el) => {
А я правильно понимаю что за один фрейм мы не можем создать несколько башен? Если так, то лучше for и как найдем нужную -  break. Если я не понял и можем создать несколько то да, так норм

2023-04-25 04:28 UTC, Olegas commented on packages/client/src/game/Game.ts
> +              buildings.sort((a, b) => {
Если мы несколько раз можем добавить элемент в buildings то лучше отстортировать один раз, когда закончим добавлять

2023-04-26 13:13 UTC, tamerlan2451 commented on packages/client/src/game/Game.ts
> +              buildings.sort((a, b) => {
сделал, спасибо за фитбек

2023-04-26 13:22 UTC, tamerlan2451 commented on packages/client/src/game/Game.ts
> +        const towerList = [
тут проблема, она в том что поле объекта position не статичное, я изначально код написал так, чтобы только при клике на тайл запускался requestAnimationFrame , а при повторном клике запускается cancelAnimationFrame который убирает цикл. все попытки вынести эти данные заканчиваются неудачей, потому что при повторном клике цикл перестает работать и башня не строится )))

2023-04-26 13:26 UTC, tamerlan2451 commented on packages/client/src/game/Game.ts
> +        const towerList = [
предлагаю оставить мой вариант двух кликов, в свободной игре не будет лишнего requestAnimationFrame, только при строительстве башни

2023-04-26 18:58 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        const towerList = [
Я ничего не понял ( Что такое свободная игра? Почему башня не строится?

2023-04-28 06:00 UTC, Antidods approved these changes

2023-04-29 17:33 UTC, tamerlan2451 commented on packages/client/src/game/Game.ts
> +        const towerList = [
потому что позиция строго должна высчитываться в requestAnimationFrame, посмотрите, я вынес массив за пределы requestAnimationFrame. как вам такая оптимизация ? это максимум что можно сделать))

2023-04-29 17:34 UTC, tamerlan2451 commented on packages/client/src/game/Game.ts
> +        const towerList = [
теперь массив создается только при клике на активный тайл и удаляется сразу же при повторном клике

2023-04-29 19:18 UTC, Olegas approved these changes

2023-04-29 19:20 UTC, Olegas commented on packages/client/src/game/Game.ts
> +    const towerList = [
Вот этот массив можно вообще создать один раз в момент создания Game. Или вообще в момент объявления модуля. Он же не изменяется нигде...

2023-04-29 19:20 UTC, Olegas commented on packages/client/src/game/Game.ts
> +        img.src = './game/assets/towers/tower_list.png';
Вот этот Image тоже можно создать один раз и потом рисовать сколько хочется раз

2023-04-30 19:31 UTC, merged