Логика форума и запросы
Tarakann119/noLabel-game pull request #58
Opened 2023-04-30 18:39 UTC by Zimer-D

Логика форума и запросы

Запросы позже будут вынесены в отдельный компонент, как и урлы

2023-05-01 14:02 UTC, tmj1 approved these changes

2023-05-01 16:26 UTC, tamerlan2451 approved these changes

2023-05-01 20:42 UTC, ArkadiySamokhvalov approved these changes

2023-05-03 18:40 UTC, Olegas requested changes

2023-05-03 18:40 UTC, Olegas commented on packages/server/API/controllers/forumTopicController.ts
> +          await Emoji.destroy({ where: { message_id: forumMessage.id } });
Тут тоже должно быть все само на уровне базы

2023-05-03 18:40 UTC, Olegas commented on packages/server/API/controllers/forumMessageController.ts
> +      await Emoji.destroy({ where: { message_id: messageId } });
И тут должен срабатывать foreign key и удаление идти на уровне базы

2023-05-03 18:40 UTC, Olegas commented on packages/client/src/pages/Topic/index.tsx
> +  const fetchData = async () => {
А почему здесь не используется redux?

2023-05-07 06:29 UTC, Antidods approved these changes

2023-05-07 08:45 UTC, Zimer-D commented on packages/client/src/pages/Topic/index.tsx
> +  const fetchData = async () => {
Мне показалось использование редакса в данном случае приведет к излишнему усложнению. Нам данные по сообщениям нужны только на форуме, получили данные, отрендерили и все. Зачем их в стор записывать?

2023-05-07 09:00 UTC, Olegas commented on packages/client/src/pages/Forum/index.tsx
> +    fetchData();
Зачем здесь создавать отдельную асинхронную функцию? Вы же все равно не используете никак то что можно писать await, все равно используете then/catch?

2023-05-07 09:01 UTC, Olegas commented on packages/client/src/pages/Topic/Message/index.tsx
> +      useEffect(() => {
Хук нельзя размещать внутри условия

2023-05-07 09:02 UTC, Olegas commented on packages/client/src/pages/Topic/Message/index.tsx
> +      }, []);
Вот здесь кажется пропущена зависимость. ПОставьте проверку react-hooks/exhaustive-deps в eslint

2023-05-07 09:04 UTC, Olegas commented on packages/server/API/controllers/forumMessageController.ts
> +    const forumMessage = await ForumMessage.findByPk(messageId);
А зачем делать отдельную проверку на наличие перед удалением? Нельзя на основе ответа от метода destroy понять - была тема или нет?

2023-05-07 09:08 UTC, Olegas commented on packages/server/API/controllers/forumTopicController.ts
> +      await User.create({
Такая схема (првоерить и если нет - записать) - не надежна.
Между проверкой и записью может вклиниться другой запрос от этого же пользователя и при вставке произойдет ошибка уникального ключа. Обычно в таких случая пользуются техникой UPSERT когда в случае вставки и нарушения уникальности вы можете указать что сделать - проигнорировать или что-то обновить

2023-05-10 15:24 UTC, Olegas commented on packages/client/src/pages/Forum/index.tsx
> +    fetchData();
А функция та зачем осталась?

2023-05-10 15:26 UTC, Olegas commented on packages/client/src/pages/Topic/Message/index.tsx
> +    }, []);
Теперь получается, что если в props сменятся data.emojis, то этот effect не выполнится с новыми данными. Это так и нужно?

2023-05-10 15:27 UTC, Olegas commented on packages/client/src/pages/Topic/index.tsx
> +  const fetchData = async () => {
Записывать в стор, для того, что бы во всем приложении было одинаково.
Вот мои аргументы:
 - консистентность (приложение должно быть реализовано одним образом, если в половине приложения мы храним даныне вот так, а в другой половине - иначе, это плохо, усложняет дальнейшую поддержку, изучение приложения)
 - разделение данных и представления (при useState и хождении в сеть из компонента теряется разделение ответственности - в одном компоненте замешана и логика представления данных, и логика их хранения (API))
 - готовность к будущим изменениям (завтра вам понадобится какие-то данные НЕ на странице форума (вывести на главной последнее сообщение или наличие новых сообщений) и придется разбирать все и вытаскивать данные куда-то в другое место, если все лежит в redux - достать данные не составит труда и не придется "переписывать" форум)

2023-05-10 15:29 UTC, Olegas commented on packages/server/API/controllers/forumTopicController.ts
> +      await User.create({
Здесь комментарий относился к созданию пользователя, а не топика. upsert нужен был на User

2023-05-10 18:25 UTC, Antidods commented on packages/server/API/controllers/forumTopicController.ts
> +      await User.create({
Поправил для User

2023-05-10 18:27 UTC, Antidods commented on packages/server/API/controllers/forumMessageController.ts
> +      } as User);
@Olegas да, я знаю. Это будет отдельным пулл реквестом, я там на прокси завис конкретно, поэтому и добавил этот костыль, что бы этот таск не блокировать.

2023-05-12 18:23 UTC, Olegas requested changes

2023-05-12 18:23 UTC, Olegas commented on packages/client/src/pages/Topic/index.tsx
> +    await dispatch(deleteForumTopic({ id, navigate })).then(() => fetchData());
Зачем тут await?

2023-05-12 18:23 UTC, Olegas commented on packages/client/src/pages/Topic/index.tsx
> +  }, [dispatch]);
Когда сменится id, этот эффект не будет выполнен с новыми параметрами

2023-05-12 18:23 UTC, Olegas commented on packages/client/src/pages/Topic/index.tsx
> +    dispatch(getMessagesForTopic({ id })).then((e) => setMessages(e.payload));
Если действия убрали в redux, почему данные мы по прежнему держим в state а не берем из redux?

2023-05-12 18:23 UTC, Olegas commented on packages/client/src/pages/Topic/TypingPlace/index.tsx
> +        axios('http://localhost:3001/api/forum/messages', {
Почему часть действий убрана в redux а часть нет?

2023-05-12 18:23 UTC, Olegas commented on packages/client/src/pages/Topic/Message/index.tsx
> +      dispatch(postEmojies({ data: requestData })).then(() => fetchData());
Если отправка эмодзи должна приводить к загрузке данных, сделайте это внутри async thunk

2023-05-12 18:23 UTC, Olegas commented on packages/client/src/pages/Topic/Message/index.tsx
> +      const requestData = JSON.stringify({
Сборка в JSON должна быть рядом с API-кодом, а не в компоненте. С точки зрения компонента есть действие - отправка эмодзи. А как там оно в JSON или нет - не его задача

2023-05-12 18:23 UTC, Olegas commented on packages/client/src/pages/Forum/index.tsx
> +    dispatch(getForumTopics()).then((e) => setItems(e.payload));
Нужно не только запросы унести в redux, но и хранение данных. У вас не должно быть тут setItems, они должны идти из redux через useSelector

2023-05-13 08:52 UTC, Zimer-D commented on packages/client/src/pages/Topic/Message/index.tsx
> +      const requestData = JSON.stringify({
+

2023-05-13 08:53 UTC, Zimer-D commented on packages/client/src/pages/Topic/index.tsx
> +    await dispatch(deleteForumTopic({ id, navigate })).then(() => fetchData());
+

2023-05-13 08:53 UTC, Zimer-D commented on packages/client/src/pages/Topic/index.tsx
> +  }, [dispatch]);
+

2023-05-13 09:39 UTC, Zimer-D commented on packages/client/src/pages/Topic/index.tsx
> +    dispatch(getMessagesForTopic({ id })).then((e) => setMessages(e.payload));
+

2023-05-13 09:39 UTC, Zimer-D commented on packages/client/src/pages/Topic/Message/index.tsx
> +      dispatch(postEmojies({ data: requestData })).then(() => fetchData());
+

2023-05-13 09:39 UTC, Zimer-D commented on packages/client/src/pages/Forum/index.tsx
> +    dispatch(getForumTopics()).then((e) => setItems(e.payload));
+

2023-05-13 13:29 UTC, Olegas approved these changes

2023-05-13 14:18 UTC, merged